spring:
  profiles: development
server:
  port: 9090
bootrest:
    customproperty: hello
security:
  user:
    name: guest
    password: guest123
  oauth2:
    client:
      clientId: trustedclient
      clientSecret: trustedclient123
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
---
spring:
  profiles: production
server:
  port: 8080
bootrest:
  customproperty: hello
security:
  user:
    name: guest
    password: guest123
  oauth2:
    client:
      clientId: trustedclient
      clientSecret: trustedclient123
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid